# Generated by Django 4.2.11 on 2024-03-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='login_token',
            field=models.CharField(default='null', max_length=256),
        ),
    ]
