# Generated by Django 4.2.11 on 2024-03-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vendor_vendoremployee_store_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='store',
            new_name='store_id',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='vendor',
            new_name='vendor_id',
        ),
        migrations.RenameField(
            model_name='vendoremployee',
            old_name='vendor',
            new_name='vendor_id',
        ),
    ]
