# Generated by Django 4.2.11 on 2024-03-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_store_product_store_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.RenameField(
            model_name='vendoremployee',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
