# Generated by Django 4.2.11 on 2024-03-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_store_id_product_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.IntegerField(default=0),
        ),
    ]
