# Generated by Django 4.2.11 on 2024-03-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_product_store_productavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_sold',
        ),
        migrations.AddField(
            model_name='productavailability',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productavailability',
            name='total_unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productavailability',
            name='unit_sold',
            field=models.IntegerField(default=0),
        ),
    ]
